#!/bin/bash

# pai-docker-running
# List of running dockers
# pai-script-id=2238e226-7a1a-47ef-aa0e-163761490f0d
# Created by Eran Caballero on Mon Aug 6 09:42:03 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=2238e226-7a1a-47ef-aa0e-163761490f0d

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_2238e226-7a1a-47ef-aa0e-163761490f0d_intro() {
pai_log_sep
pai_log 'starting pai-docker-running...'
}

pai_list_running_dockers() {
        docker ps
}

pai_2238e226-7a1a-47ef-aa0e-163761490f0d_end() {
pai_log 'done :)'
}

# PAI main flow

pai_2238e226-7a1a-47ef-aa0e-163761490f0d_intro
pai_list_running_dockers
pai_2238e226-7a1a-47ef-aa0e-163761490f0d_end
