#!/bin/bash

# pai-docker-info
# Info from naked docker bot
# pai-script-id=56e779f2-dcf7-4309-9fa2-8aff9f6261b5
# Created by Eran Caballero on Mon Aug 6 09:22:13 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=56e779f2-dcf7-4309-9fa2-8aff9f6261b5

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_56e779f2-dcf7-4309-9fa2-8aff9f6261b5_intro() {
pai_log_sep
pai_log 'starting pai-docker-info...'
}

pai_info_docker() {
        docker info
}

pai_56e779f2-dcf7-4309-9fa2-8aff9f6261b5_end() {
pai_log 'done :)'
}

# PAI main flow

pai_56e779f2-dcf7-4309-9fa2-8aff9f6261b5_intro
pai_info_docker
pai_56e779f2-dcf7-4309-9fa2-8aff9f6261b5_end
