#!/bin/bash

# pai-docker-start
# Start naked docker bot
# pai-script-id=18e8242d-46b2-41a4-9b55-e52117aa4b11
# Created by Eran Caballero on Mon Aug 6 09:21:30 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=18e8242d-46b2-41a4-9b55-e52117aa4b11

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_18e8242d-46b2-41a4-9b55-e52117aa4b11_intro() {
pai_log_sep
pai_log 'starting pai-docker-start...'
}

pai_start_docker_container() {
        docker start $1
}

pai_18e8242d-46b2-41a4-9b55-e52117aa4b11_end() {
pai_log 'done :)'
}

# PAI main flow

pai_18e8242d-46b2-41a4-9b55-e52117aa4b11_intro
pai_start_docker_container $1
pai_18e8242d-46b2-41a4-9b55-e52117aa4b11_end
