#!/bin/bash

# pai-docker-delete
# Delete naked docker bot
# pai-script-id=3adc8220-b30b-4c6f-8e78-52b883749da0
# Created by Eran Caballero on Mon Aug 6 09:22:48 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=3adc8220-b30b-4c6f-8e78-52b883749da0

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_3adc8220-b30b-4c6f-8e78-52b883749da0_intro() {
pai_log_sep
pai_log 'starting pai-docker-delete...'
}

pai_delete_docker_container() {
	docker rm $1
}

pai_3adc8220-b30b-4c6f-8e78-52b883749da0_end() {
pai_log 'done :)'
}

# PAI main flow

pai_3adc8220-b30b-4c6f-8e78-52b883749da0_intro
pai_delete_docker_container $1
pai_3adc8220-b30b-4c6f-8e78-52b883749da0_end
