#!/bin/bash

# pai-docker-stop
# Stop naked docker bot
# pai-script-id=ae36c0da-036f-488f-ba1b-cbd4967befc9
# Created by Eran Caballero on Mon Aug 6 09:20:18 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=ae36c0da-036f-488f-ba1b-cbd4967befc9

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_ae36c0da-036f-488f-ba1b-cbd4967befc9_intro() {
pai_log_sep
pai_log 'starting pai-docker-stop...'
}

pai_stop_docker_container() {
        docker stop $1
}

pai_ae36c0da-036f-488f-ba1b-cbd4967befc9_end() {
pai_log 'done :)'
}

# PAI main flow

pai_ae36c0da-036f-488f-ba1b-cbd4967befc9_intro
pai_stop_docker_container $1
pai_ae36c0da-036f-488f-ba1b-cbd4967befc9_end
