#!/bin/bash

# pai-storage
# PAI CODE Storage Module
# pai-script-id=27BC401B-375B-4793-BD70-5BF7842A0A24
# Created by Tamir Fridman on Mon May 28 18:30:53 IDT 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_27BC401B-375B-4793-BD70-5BF7842A0A24_intro() {
pai_log_sep
pai_log 'starting pai-storage...'
}

pai_27BC401B-375B-4793-BD70-5BF7842A0A24_end() {
pai_log 'done :)'
}

# PAI main flow

pai_27BC401B-375B-4793-BD70-5BF7842A0A24_intro



case "$1" in
        validate-folder)
			echo "creating $2"
            pai_validate_folder $2 
            ;;
         
        *)
            echo $"pai-storage:  validate-folder"
            exit 1
 
esac

pai_27BC401B-375B-4793-BD70-5BF7842A0A24_end
