#!/bin/bash

# pai-bot Restart
# PAI-Bot pull & start
# pai-script-id=a2e1e767-fbb1-4444-a7cc-f1b7507c21f1
# Created by Eran Caballero on Mon Dev 03 11:26:46 IDT 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=a2e1e767-fbb1-4444-a7cc-f1b7507c21f1

PAI=/var/PAI
PAI_BOT_JS_FOLDER=/var/PAI/Bot/PAI-BOT-JS
PM2_BOT_ID=0

. $PAI/System/pai.sh

# PAI functions

pai_a2e1e767-fbb1-4444-a7cc-f1b7507c21f1_intro() {
pai_log_sep
pai_log 'starting pai-node-3000-pull...'
}

pai_bot_restart() {
cd $PAI_BOT_JS_FOLDER && \
git reset --hard && \
echo ""
echo "Running BOT git pull"
git pull && \
echo ""
echo "Running Npm install"
npm i && \
echo ""
echo "Restarting bot"
pm2 restart $PM2_BOT_ID
}

pai_a2e1e767-fbb1-4444-a7cc-f1b7507c21f1_end() {
pai_log 'done :)'
}

# PAI main flow

pai_a2e1e767-fbb1-4444-a7cc-f1b7507c21f1_intro
pai_bot_restart
pai_a2e1e767-fbb1-4444-a7cc-f1b7507c21f1_end
