#!/bin/bash

# pai-install
# PAI OS for Linux
# pai-script-id=3C1F2ED5-C28A-40EF-835E-9D93B8502C6E
# Created by Ron Fridman on Mon nov 26 18:01:48 IDT 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

# PAI=/var/PAI
PAI_BACKUP_FOLDER=$PAI/Backup
PAI_BOT_FOLDER=$PAI/Bot
PAI_LOGS_FOLDER=$PAI/Logs
PAI_SYSTEM_FOLDER=$PAI/System
PAI_STARTUP_FOLDER=$PAI/Startup

#PAI_SCRIPT_GUID=$(uuidgen)
PAI_SCRIPT_ID=3C1F2ED5-C28A-40EF-835E-9D93B8502C6E


RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

# PAI functions

pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C6E_intro() {
#	touch $PAI_CONFIG_FILE

	echo 'validating PAI environment...'
	echo '-----------------------------'
}

echoerr() { echo "${RED} $@ ${NORMAL}" 1>&2; }
echosuccess() { echo "${GREEN} $@ ${NORMAL}" 1>&2; }

pai_validate_folder_exists() #Ubuntu
{
	if ! [ -d $1 ] 
		then
			echoerr "Missing folder: $1 folder not exist"
			SUCCESS=false
			
	fi
}



pai_validate_folders() {
	
	pai_validate_folder_exists $PAI
	pai_validate_folder_exists $PAI_BACKUP_FOLDER
	pai_validate_folder_exists $PAI_BOT_FOLDER
	pai_validate_folder_exists $PAI_LOGS_FOLDER
	pai_validate_folder_exists $PAI_SYSTEM_FOLDER
	pai_validate_folder_exists $PAI_STARTUP_FOLDER
}

pai_validate_variable() 
{
	SUCCESS=false
	if [ -z "$PAI" ];
		then
			echoerr "\$PAI Variable is not exists !";
		  SUCCESS=false;
		else 
		  SUCCESS=true
		  pai_validate_folders;
 	fi

}

pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C6E_end() {
	
	echo '-----------------------------'

 	if $SUCCESS;
 		then
 			echosuccess " ✔ All set. Your PAI environment is ready! ";
		else
			echoerr " ✖ PAI environment is not set properly! ";
	fi
}

# PAI main flow

pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C6E_intro
pai_validate_variable
pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C6E_end