#!/bin/bash

# pai-install-bot
# Install Nodejs Bot
# pai-script-id=
# Created by Eran Caballero on Wed Aug 1 11:45:01 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved

#Exit incase of error
set -e

# PAI includes

PAI_SCRIPT_ID=

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_intro() {
pai_log_sep
pai_log 'starting pai-install-bot...'
}

pai_install_nodejs_pm2() {
#Install nodejs
apt-get install sudo curl
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && \
apt-get install -qq -y nodejs

#Install PM2
npm install pm2 -g
}

pai_install_bot() {
#git clone https://github.com/PAI-Tech/PAI-BOT-JS.git
cd PAI-BOT-JS
npm login
npm install
node PAI.js
}

pai_end() {
pai_log 'done :)'
}

# PAI main flow

pai_intro
pai_install_nodejs_pm2
pai_install_bot
pai_end
