#!/bin/bash

# pai-backup-bot
# Backup Bot and keep 7 days
# pai-script-id=8fc5a3dd-ba8d-4cd4-51ce-7e0ae086b245
# Created by Eran Caballero on Thr Nov 29 12:15:27 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved

# PAI includes

PAI_SCRIPT_ID=8fc5a3dd-ba8d-4cd4-51ce-7e0ae086b245

PAI=/var/PAI
BOT_NAME=Bot
PAI_BOT_FOLDER=$PAI/Bot
BACKUP_FOLDER="$PAI/Backup"
PAI_BOT_BACKUP_FOLDER=$BACKUP_FOLDER/Bot
_now=$(date +"%m_%d_%Y-%H.%M")

. $PAI/System/pai.sh

# PAI functions

pai_8fc5a3dd-ba8d-4cd4-51ce-7e0ae086b245_intro() {
pai_log_sep
pai_log 'starting pai-backup-mysql-db...'
}

pai_backup()
{
	pai_log_sep
	pai_log 'Validating backup folder'
	pai_validate_folder $BACKUP_FOLDER
	pai_validate_folder $PAI_BOT_BACKUP_FOLDER
	pai_log 'Starting backing-up PAI-Bot folder...'
	tar -zcvf $PAI_BOT_BACKUP_FOLDER/$BOT_NAME-$_now.tar.gz -C $PAI/ ./$BOT_NAME
	ls -l $PAI_BOT_BACKUP_FOLDER
        find $PAI_BOT_BACKUP_FOLDER/$BOT_NAME* -mtime +7 -exec rm {} \;
}

pai_8fc5a3dd-ba8d-4cd4-51ce-7e0ae086b245_end() {
pai_log 'done :)'
}

# PAI main flow

pai_8fc5a3dd-ba8d-4cd4-51ce-7e0ae086b245_intro
pai_backup
pai_8fc5a3dd-ba8d-4cd4-51ce-7e0ae086b245_end
