#!/bin/bash

# pai-docker-start
# Start Restore Mongo DB
# pai-script-id=28e8242d-46b2-41a6-9b55-e52117aa4b11
# Created by Eran Caballero on Mon Aug 6 09:21:30 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=28e8242d-46b2-41a6-9b55-e52117aa4b11

PAI=/var/PAI
USERNAME=$1
PASSWORD=$2

. $PAI/System/pai.sh

# PAI functions

pai_28e8242d-46b2-41a6-9b55-e52117aa4b11_intro() {
pai_log_sep
pai_log 'starting restoring Mongo DB...'
}

pai_mongo_backup() {
	# $1=USERNAME | $2=PASSWORD
	mongorestore --db admin -u $USERNAME -p $PASSWORD --drop /var/PAI/Backup/admin
}

pai_28e8242d-46b2-41a6-9b55-e52117aa4b11_end() {
pai_log 'done :)'
}

# PAI main flow

pai_28e8242d-46b2-41a6-9b55-e52117aa4b11_intro
pai_mongo_backup $1 $2
pai_28e8242d-46b2-41a6-9b55-e52117aa4b11_end
