#!/bin/bash

# pai-create-startup
# Create startup file that will run in Restart
# pai-script-id=c24f54c3-c8c5-4d2d-9b26-c606403cb756
# Created by Eran Caballero on Mon Jun 25 15:00:32 IDT 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=c24f54c3-c8c5-4d2d-9b26-c606403cb756

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI variables

PAI_STARTUP_SCRIPT_FILE=pai-startup.sh
PAI_STARTUP_FOLDER=/var/PAI/Startup
PAI_STARTUP_SCRIPT_FILE_PATH=$PAI_STARTUP_FOLDER/$PAI_STARTUP_SCRIPT_FILE
INIT_FOLDER=/etc/init.d
PAI_STARTUP_SCRIPT_FILE_LINK=pai-startup
PAI_INSTALLER_NAME="Pai Startup"

# PAI functions

pai_c24f54c3-c8c5-4d2d-9b26-c606403cb756_intro() {
pai_log_sep
pai_log 'starting pai-create-startup...'
}

pai_write_to_script()
{
	echo -e $1>>$PAI_STARTUP_SCRIPT_FILE_PATH
}

pai_create_startup_file()
{
	# checking if startup folder exists
	pai_validate_folder $PAI_STARTUP_FOLDER

	if [ -f $PAI_STARTUP_SCRIPT_FILE ]; then
		touch $PAI_STARTUP_SCRIPT_FILE_PATH
	else
		cp $PAI/System/pai-startup-empty.sh $PAI_STARTUP_SCRIPT_FILE_PATH
	fi

	pai_write_to_script ""
	pai_write_to_script "SCRIPT_NAME=pai-run-q-processor.sh"
	pai_write_to_script "DESC=Pai processor"
	pai_write_to_script "SCRIPT_NAME_SH=/var/PAI/Media/processor/pai-run-q-processor.sh"
	pai_write_to_script ""
	pai_write_to_script '$SCRIPT_NAME_SH'

	chmod +x $PAI_STARTUP_SCRIPT_FILE_PATH

	if [ -f $PAI_STARTUP_SCRIPT_FILE_LINK ]; then
		pai_log "removing startup definitions"
		rm $PAI_STARTUP_SCRIPT_FILE_LINK
		update-rc.d -f $PAI_STARTUP_SCRIPT_FILE_LINK remove
	fi

	ln -s $PAI_STARTUP_SCRIPT_FILE_PATH $INIT_FOLDER/$PAI_STARTUP_SCRIPT_FILE_LINK
	update-rc.d $PAI_STARTUP_SCRIPT_FILE_LINK

}

pai_c24f54c3-c8c5-4d2d-9b26-c606403cb756_end() {
pai_log 'done :)'
}

# PAI main flow

pai_c24f54c3-c8c5-4d2d-9b26-c606403cb756_intro
pai_c24f54c3-c8c5-4d2d-9b26-c606403cb756_end
