#!/bin/bash

# pai-backup-all-dockers
# Backup all docker containers to desctination folder
# pai-script-id=dc11a103-5b41-4e7d-b47b-adefa6fa3528
# Created by Ron Fridman on Wed Nov 28 15:31:50 IST 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=dc11a103-5b41-4e7d-b47b-adefa6fa3528

PAI=/var/PAI
DESTINATION=$1 # destination path of backup folder

. $PAI/System/pai.sh

# PAI functions

pai_dc11a103-5b41-4e7d-b47b-adefa6fa3528_intro() {
	pai_log_sep
	pai_log 'starting pai-backup-all-dockers...'
}


pai_backup_docker_container() {
	pai_log_sep


	containers=$(sudo docker ps | awk '{if(NR>1) print $NF}') # all containers names splitted with space


	pai_commit_dockers $containers

	echo "destination $destination" 

}


pai_commit_dockers() {
	for var in "$@"
	do

		docker_container_name="$var"
		docker_image_name="img_$var"
		docker_backup_file_name="$DESTINATION/BKP_$var.tar"

		pai_log "starting to backup container: $var" 

		docker commit $docker_container_name $docker_image_name

		pai_log "save to file: $var"
		docker save $docker_image_name > $docker_backup_file_name

		pai_log "docker container backed up"

		pai_log_sep

	done
}

pai_dc11a103-5b41-4e7d-b47b-adefa6fa3528_end() {
	pai_log 'done :)'
}

# PAI main flow

pai_dc11a103-5b41-4e7d-b47b-adefa6fa3528_intro
pai_backup_docker_container $1
pai_dc11a103-5b41-4e7d-b47b-adefa6fa3528_end
