#!/bin/bash

# pai-install-docker-bot
# Create pai-bot docker
# pai-script-id=206b5dff-0a91-4b33-8715-41f12a280c50
# Created by Eran Caballero on Thu Aug 2 15:58:07 UTC 2018
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI_SCRIPT_ID=206b5dff-0a91-4b33-8715-41f12a280c50

PAI=/var/PAI

. $PAI/System/pai.sh

# PAI functions

pai_206b5dff-0a91-4b33-8715-41f12a280c50_intro() {
pai_log_sep
pai_log 'starting pai-install-docker-bot...'
}

pai_20_bot() {
./pai-install-docker-bot.sh "pai-bot-test-1" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-2" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-3" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-4" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-5" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-6" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-7" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-8" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-9" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-10" "Hi"
./pai-install-docker-bot.sh "pai-bot-test-11" "Hi"
}

pai_206b5dff-0a91-4b33-8715-41f12a280c50_end() {
pai_log 'done :)'
}

# PAI main flow

pai_206b5dff-0a91-4b33-8715-41f12a280c50_intro
pai_20_bot
pai_206b5dff-0a91-4b33-8715-41f12a280c50_end
