#!/bin/bash

# pai-install Bot on Sawtooth bc dockers
# PAI OS for Linux
# pai-script-id=3C1F2ED5-C28A-40EF-835E-9D93B8502C8E
# Created by Eran Caballero on Thr Jan 16 12:01:48 IDT 2019
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2018, all rights reserved


# PAI includes

PAI=/var/PAI
PAI_BACKUP_FOLDER=$PAI/Backup
PAI_BACKUP_MYSQL_FOLDER=$PAI_BACKUP_FOLDER/MySQL
PAI_BOT_FOLDER=$PAI/Bot
PAI_BOT_TEST_FILE=$PAI_BOT_FOLDER/test.sh
PAI_BOT_CONFIG_FILE=$PAI_BOT_FOLDER/$PAI_NET_ID/settings/strings.cfg
PAI_CONFIG_FOLDER=$PAI/Config
PAI_CONFIG_FILE=$PAI_CONFIG_FOLDER/pai.config
PAI_LOGS_FOLDER=$PAI/Logs
PAI_SYSTEM_FOLDER=$PAI/System
PAI_STARTUP_FOLDER=$PAI/Startup
PAI_CODE_FOLDER=$PAI/PAI-CODE/
PAI_CODE_MODULES_FOLDER=$PAI_CODE_FOLDER/Modules
PAI_EXTERNAL_SCRIPT_FOLDER=$PAI_CODE_FOLDER/external-scripts

#PAI_SCRIPT_GUID=$(uuidgen)
PAI_SCRIPT_ID=3C1F2ED5-C28A-40EF-835E-9D93B8502C8E

#. ./pai.sh

# PAI functions

pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C6E_intro() {
#	touch $PAI_CONFIG_FILE
#	pai_log_sep
	echo -e 'starting pai-install...'
	echo ""
}

pai_install_prereq() {
#	pai_log_sep
	echo ""
	echo -e 'Installing pre-req'
	apt-get update
	apt-get install -qq -y htop nano sudo git curl wget
	curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && \
	apt-get install -qq -y nodejs
	npm install -g npm
	npm install -g pm2
	pm2 startup
	echo ""
}

pai_install_env_and_bot() {
#	pai_log_sep
	echo -e 'Installing PAI env'
	cd /home
	git clone https://github.com/PAI-Tech/PAI-BOT-JS.git && \
	git clone https://github.com/PAI-Tech/PAI-OS-LINUX.git
	cd PAI-OS-LINUX/Install/ && ./pai-install.sh
	echo""
	echo -e 'Installing Bot'
	cd /home && rm -rf /home/PAI-OS-LINUX
	mv PAI-BOT-JS $PAI_BOT_FOLDER
	$PAI_SYSTEM_FOLDER/pai-install-bot.sh
}

pai_update_config_file() {
	echo "OS GUID: $PAI_SCRIPT_ID" >> $PAI_CONFIG_FILE
	echo Installation time: "$(date)" >> $PAI_CONFIG_FILE
}

pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C8E_end() {
	echo ""
	echo -e 'done :)'
}

# PAI main flow

pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C6E_intro
pai_install_prereq
pai_install_env_and_bot
pai_update_config_file
pai_3C1F2ED5-C28A-40EF-835E-9D93B8502C8E_end
