#!/bin/bash
# pai-install-raspi-4.sh
# Install new raspberryPI instance
# pai-script-id=9729e1er-60d7-42cb-8f01-dcf075b4cbf9
# Created by Eran Caballero on Wed June 28 10:20:08 UTC 2020
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2020, all rights reserved

# PAI includes

PAI=/var/PAI
PAI_LOGS=$PAI/Logs

. $PAI/System/pai.sh

PAI_INSTALLER_NAME="Pai Prepare Linux Ubuntu"

# PAI functions

pai_9729e1ee-60d7-42cb-8f01-dcf075b4cbf9_intro()
{
	pai_log "Prepairing Linux OS For Pai"
}

pai_update_os()
{
	pai_log "Updating OS & Installing Default (Linux)..."
	PAI_REQUIERED_PREPARE_INSTALLATION="pydf zip unzip htop git build-essential gcc g++ make libssl-dev libffi-dev software-properties-common python-dev python-numpy python-tk python3-dev python3-tk python3-numpy"
	apt-get -qq update
	apt-get -qq install $PAI_REQUIERED_PREPARE_INSTALLATION
	#apt-get -qq -y upgrade
	pai_log "OS updated :)"
}

pai_update_locale()
{
	locale-gen "he_IL.UTF-8"
	locale-gen "en_US.UTF-8"
	#dpkg-reconfigure locales #IBM
	update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 #MS
	timedatectl set-timezone Etc/UTC
	pai_log "Locale (UTF+TZ) updated"
}

pai_handle_sudoers()
{
	pai_log "Handling Sudoers"
	dpkg-statoverride --update --add root sudo 4750 /bin/su
}

pai_update_profiles()
{
	if grep -r "PAI :]" "/etc/profile";
	then 
		pai_log "Profile file already updated"
	else
		echo "# PAI :]" >> /etc/profile
		echo "PAI=/var/PAI" >> /etc/profile
		echo "" >> /etc/profile
		echo "LD_LIBRARY_PATH=/usr/local/lib/" >> /etc/profile
		echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/" >> /etc/profile
		echo "" >> /etc/profile
		. /etc/profile
#		echo "nameserver 8.8.8.8" >> /etc/resolv.conf
		pai_log "Profile file updated"
	fi
}

pai_ssh_setup()
{
	SSHD_CONFIG_FILE="/etc/ssh/sshd_config"
	pai_log "Reconfigure password authentication"
	sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/' $SSHD_CONFIG_FILE
	apt-get install openssh-client openssh-server openssh-sftp-server
	service ssh restart
	pai_log "Done..."
}

pai_nodejs_install()
{
        # Installing Nodejs
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && \
        apt-get install -qq -y nodejs
        npm i -g forever
}

#git clone https://github.com/PAI-Tech/PAI-OS-LINUX.git
	

# PAI MAIN FLOW

pai_9729e1ee-60d7-42cb-8f01-dcf075b4cbf9_intro
pai_update_os
pai_update_locale
pai_handle_sudoers
pai_update_profiles
pai_ssh_setup
pai_nodejs_install
